### ISSUE TITLE
cifar10 training error: RuntimeError: shape '[128, 128, 3, 3, 1]' is invalid for input of size 73728

### ISSUE THREAD

**Issue by liweintu** [zhoujuncc1/shenjingcat#3]
**Process to trigger this error:** After cd-ing into shenjingcat/examples/cifar10, running the following command.
python3 cifar10.py

**The following error is shown:**
Train Epoch: 14 [1036800/1050000 (99%)]	Loss: 0.342132
Train Epoch: 14 [1044480/1050000 (99%)]	Loss: 0.332377

Test set: Average loss: 0.1205, Accuracy: 47915/50000 (96%)

Test set: Average loss: 0.2914, Accuracy: 9093/10000 (91%)

Traceback (most recent call last):
  File "cifar10.py", line 190, in <module>
    main()
  File "cifar10.py", line 182, in main
    transfer_model(model, snn_model)
  File "/home/liwei/python3-venv/env/lib/python3.6/site-packages/catSNN-0.0.0-py3.6.egg/catSNN/transfer.py", line 12, in transfer_model
RuntimeError: shape '[128, 128, 3, 3, 1]' is invalid for input of size 73728

**Environment info:**
OS: Ubuntu 18.04.5 LTS
python version: 3.6.9
PyTorch version: 1.7.1

**Comment by zhoujuncc1** [comment]
It is due to the inconsistancy of CNN and SNN model. The latest commit ca0d8d55baa865265fbd29d8e8a5fc8e11a74927 solves the problem.
